[project]
name = "project-2-krutikova-m26-555"
version = "0.1.0"
description = "Primitive DB — учебный проект"
readme = "README.md"
authors = [
    { name = "Kseniia Krutikova", email = "ks-krutikova@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "prompt>=0.4.1",
]

[project.scripts]
project = "src.primitive_db.main:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src.primitive_db"
module-root = ""
